In [1]:
import pandas as pd
import numpy as np
from pandas_profiling import ProfileReport
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn import svm
from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv('chrome_reviews.csv')
df.head()

ID                                         Review URL  \
0  3886  https://play.google.com/store/apps/details?id=...   
1  3887  https://play.google.com/store/apps/details?id=...   
2  3888  https://play.google.com/store/apps/details?id=...   
3  3889  https://play.google.com/store/apps/details?id=...   
4  3890  https://play.google.com/store/apps/details?id=...   

                                             Text  Star  Thumbs Up  \
0                      This is very helpfull aap.     5          0   
1                                            Good     3          2   
2  Not able to update. Neither able to uninstall.     1          0   
3                                        Nice app     4          0   
4                               Many unwanted ads     1          0   

          User Name Developer Reply        Version Review Date  \
0  INDIAN Knowledge             NaN  83.0.4103.106  2020-12-19   
1  Ijeoma Happiness             NaN  85.0.4183.127  2020-12-19   
2  Priti D BtCFs-29             NaN  85.0.4183.127  2020-12-19   
3        Ajeet Raja             NaN  77.0.3865.116  2020-12-19   
4           Rams Mp             NaN   87.0.4280.66  2020-12-19   

               App ID  
0  com.android.chrome  
1  com.android.chrome  
2  com.android.chrome  
3  com.android.chrome  
4  com.android.chrome

In [3]:
df.shape

(7204, 10)

In [4]:
#ProfileReport(df)

In [12]:
df.isna()

ID  Review URL   Text   Star  Thumbs Up  User Name  Developer Reply  \
0     False       False  False  False      False      False             True   
1     False       False  False  False      False      False             True   
2     False       False  False  False      False      False             True   
3     False       False  False  False      False      False             True   
4     False       False  False  False      False      False             True   
...     ...         ...    ...    ...        ...        ...              ...   
7199  False       False  False  False      False      False             True   
7200  False       False  False  False      False      False             True   
7201  False       False  False  False      False      False             True   
7202  False       False  False  False      False      False             True   
7203  False       False  False  False      False      False             True   

      Version  Review Date  App ID  
0       False        False   False  
1       False        False   False  
2       False        False   False  
3       False        False   False  
4       False        False   False  
...       ...          ...     ...  
7199    False        False   False  
7200    False        False   False  
7201    False        False   False  
7202    False        False   False  
7203    False        False   False  

[7204 rows x 10 columns]

In [5]:
type((df.isna().sum()).to_list())

list

In [6]:
(df.isna().sum()).to_list()

[0, 0, 1, 0, 0, 0, 7109, 85, 0, 0]

In [10]:
sum((df.isna().sum()).to_list())

7195

In [11]:
if sum((df.isnull().sum()).to_list()) > 0:
    print("hello")

hello


In [6]:
df = df[['Text','Star']]
df.head()

Text  Star
0                      This is very helpfull aap.     5
1                                            Good     3
2  Not able to update. Neither able to uninstall.     1
3                                        Nice app     4
4                               Many unwanted ads     1

In [7]:
df.dropna(inplace=True)

In [8]:
df['sentiments'] = df.Star.apply(lambda x: 0 if x in [1, 2] else 1)

In [9]:
df.head()

Text  Star  sentiments
0                      This is very helpfull aap.     5           1
1                                            Good     3           1
2  Not able to update. Neither able to uninstall.     1           0
3                                        Nice app     4           1
4                               Many unwanted ads     1           0

In [10]:
x = df['Text']
x.head()

0                        This is very helpfull aap.
1                                              Good
2    Not able to update. Neither able to uninstall.
3                                          Nice app
4                                 Many unwanted ads
Name: Text, dtype: object

In [11]:
y = df[['sentiments']]
y.head()

sentiments
0           1
1           1
2           0
3           1
4           0

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=45)

In [13]:
X_train

2553                                            Great app
4719    Won't update bc System Web-view won't update i...
4488                 Please open my facebook with my data
3776                                     Its not updating
2218                                                 Nice
                              ...                        
3616                                            Thank you
6013                                               Supare
5764                            It doesn't want to update
6559                                      Its best to use
7116                                                 Sulo
Name: Text, Length: 5762, dtype: object

In [14]:
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(5762,) (1441,) (5762, 1) (1441, 1)


In [15]:
#tfidf vectorizer
vectorizer = TfidfVectorizer()

In [16]:
X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [17]:
X_train_vec

<5762x4674 sparse matrix of type '<class 'numpy.float64'>'
	with 33674 stored elements in Compressed Sparse Row format>

In [18]:
X_train_vec.shape

(5762, 4674)

In [19]:
lr = LogisticRegression()
lr.fit(X_train_vec, y_train)

C:\Users\sonaw\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


LogisticRegression()

In [20]:
y_pred_lr = lr.predict(X_test_vec)

In [21]:
lr_score = lr.score(X_test_vec, y_test)
print("Results for Logistic Regression with tfidf")
print(lr_score)

Results for Logistic Regression with tfidf
0.8369188063844553


In [22]:
y_pred_lr = lr.predict(X_test_vec)

In [23]:
#Confusion matrix
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, y_pred_lr)

array([[312, 142],
       [ 93, 894]], dtype=int64)

In [24]:
#params = {'kernel':('linear', 'rbf'), 'C':[1, 10, 100]}
svcl = svm.SVC(kernel = 'rbf')
#clf_sv = GridSearchCV(svcl, params)
svcl.fit(X_train_vec, y_train)

C:\Users\sonaw\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVC()

In [25]:
svcl_score = svcl.score(X_test_vec, y_test)
print("Results for Support Vector Machine with tfidf: ",svcl_score)

Results for Support Vector Machine with tfidf:  0.8480222068008327


In [26]:
y_pred_sv = svcl.predict(X_test_vec)

In [27]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred_sv).ravel()
print(tn, fp, fn, tp)
tpr_sv = round(tp/(tp + fn), 4)
tnr_sv = round(tn/(tn+fp), 4)
print(tpr_sv, tnr_sv)

335 119 100 887
0.8987 0.7379


In [28]:
#Confusion matrix
cm_sv = confusion_matrix(y_test, y_pred_sv)
cm_sv

array([[335, 119],
       [100, 887]], dtype=int64)

In [29]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred_sv).ravel()
print("tn: ",tn,"fp:",fp,"fn: ",fn,"tp:",tp)
tpr_sv = round(tp/(tp + fn), 4)
tnr_sv = round(tn/(tn+fp), 4)
print("tpr_sv: ",tpr_sv, "tnr_sv: ",tnr_sv)

tn:  335 fp: 119 fn:  100 tp: 887
tpr_sv:  0.8987 tnr_sv:  0.7379


In [30]:
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train_vec, y_train)

C:\Users\sonaw\anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:179: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier()

In [31]:
knn_score = knn.score(X_test_vec, y_test)
print("Results for KNN Classifier with tfidf: ",knn_score)

Results for KNN Classifier with tfidf:  0.7571131158917418


In [32]:
y_pred_knn = knn.predict(X_test_vec)

In [33]:
#Confusion matrix
cm_knn = confusion_matrix(y_test, y_pred_knn)
cm_knn

array([[143, 311],
       [ 39, 948]], dtype=int64)

In [34]:
tn, fp, fn, tp = confusion_matrix(y_test, y_pred_knn).ravel()
print("tn: ",tn,"fp:",fp,"fn: ",fn,"tp:",tp)
tpr_knn = round(tp/(tp + fn), 4)
tnr_knn = round(tn/(tn+fp), 4)
print("tpr_sv: ",tpr_sv, "tnr_sv: ",tnr_sv)

tn:  143 fp: 311 fn:  39 tp: 948
tpr_sv:  0.8987 tnr_sv:  0.7379


In [6]:
data = pd.read_csv("browser_rankings_data.csv",skiprows=1)
data.head()

ID  Keyword  Rank Country Language        Date                  App ID  \
0   1  browser   2.0      in       en  2020-12-16    net.fast.web.browser   
1   2  browser   3.0      in       en  2020-12-16      com.android.chrome   
2   3  browser   4.0      in       en  2020-12-16       com.opera.browser   
3   3  browser   4.0      in       en  2020-12-16       com.opera.browser   
4   4  browser   1.0      in       en  2020-12-16  com.cloudmosa.puffinTV   

  Date of Last Description Change  \
0                      2020-12-18   
1                      2020-12-18   
2                      2021-02-27   
3                      2020-12-18   
4                      2021-02-07   

                                   Short Description  \
0  The small, fastest, secure Web Browser, best m...   
1  Fast, simple, and secure. Google Chrome browse...   
2  Fast, safe web browser: free VPN, Ad blocker, ...   
3  Fast, safe web browser: free VPN, Ad blocker, ...   
4  Puffin TV Browser - One App to Watch All Video...   

                                    Long Description  
0  One of the smallest, fastest, secure Web Brows...  
1  Google Chrome is a fast, easy to use, and secu...  
2  Fast, safe and private, introducing the latest...  
3  Opera is a fast, safe web browser for your And...  
4  Puffin TV Browser is a special edition of Puff...

In [7]:
data = data[["Short Description","Long Description","Rank"]]
data.head()

Short Description  \
0  The small, fastest, secure Web Browser, best m...   
1  Fast, simple, and secure. Google Chrome browse...   
2  Fast, safe web browser: free VPN, Ad blocker, ...   
3  Fast, safe web browser: free VPN, Ad blocker, ...   
4  Puffin TV Browser - One App to Watch All Video...   

                                    Long Description  Rank  
0  One of the smallest, fastest, secure Web Brows...   2.0  
1  Google Chrome is a fast, easy to use, and secu...   3.0  
2  Fast, safe and private, introducing the latest...   4.0  
3  Opera is a fast, safe web browser for your And...   4.0  
4  Puffin TV Browser is a special edition of Puff...   1.0

In [8]:
data.corr()

Rank
Rank   1.0